### PR TITLE
Filter never been called

### PR DESCRIPTION
**Pull request by msalaj**

### CODE REVIEW

**Comment by elindydotcom** [comment]
Ah, I see - looks like the filter name was declared with single quotes instead of double quotes so the variable references inside it were not resolved.  I think that might be the only change needed - no need to assign the app name to a var first?

**Comment by msalaj** [comment]
I think it needs to be variable to work: "something{$variable}something

**Comment by msalaj** [comment]
https://www.php.net/manual/en/language.types.string.php#language.types.string.parsing.complex

The expression is written the same way as it would appear outside the string, and then wrapped in { and }. Since { can not be escaped, this syntax will only be recognised when the $ immediately follows the {. Use {\$ to get a literal {$.

**Comment by elindydotcom** [comment]
This PR included a new filter used in the server actions column.  A new commit has updated the names of those filters. See this commit: https://github.com/WPCloudDeploy/wp-cloud-deploy/commit/bbdcf9d901d9459549421df25421be477e5d6053.

You might want to update your custom code to call both the old and new filter names so that your custom code still works when you update wpcd code later.  (Or pull the latest dev branch.)

**Comment by msalaj** [comment]
thank you!

**Pull request merged**
